---
- name: Start docker nginx:latest
  hosts: localhost.test
  become: false  # Requires sudo privileges

  tasks:
    - name: Start a nginx docker container
      docker_container:
        name: my_nginx_container
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8089:80"
      when:
        - run_container | default(false) | bool
        - control_container | default(false) | bool

    - name: Stop a Docker container
      check_mode: no
      docker_container:
        name: my_nginx_container
        state: stopped
      when:
        - stop_container | default(false) | bool
        - control_container | default(false) | bool
        
    - name: Remove a Docker container
      docker_container:
        name: my_nginx_container
        state: absent
      tags:
      - remove_container