---
- name: "vm snapshot creation test"
  hosts: localhost 
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: "Snapshot create"
      vmware_guest_snapshot:
        hostname: ***********
        username: "**********"
        password: "*******"
        datacenter: *********
        folder: "*******"
        name: "ansible-Test"
        state: present
        snapshot_name: sampel_snapshot
        description: snap1_description
        validate_certs: false
